### ISSUE TITLE
Typescript declaration is missing

### ISSUE THREAD

**Issue by khitrenovich** [keveightysev/us-state-converter#4]
Providing TS declaration would help a lot in adoption.

This is the basic `d.ts` I've used internally - 

```
// This is definitelty incomplete.
// For the full API, refer to https://github.com/keveightysev/us-state-converter/blob/master/README.md

declare module 'us-state-converter' {
  type StateInfo = {
    name: string;
    usps: string;
    demonym: string;
    iso: string;
    altAbbr: string[];
    uscg: string;
  };
  type Converter = (string) => StateInfo | undefined;
  const converter: Converter;
  export default converter;
}
```

**Comment by tharinduAppno** [comment]
thanks @khitrenovich
and we can add other functions as well, 

`declare module 'us-state-converter' {
  type StateInfo = {
    name: string;
    usps: string;
    demonym: string;
    iso: string;
    altAbbr: string[];
    uscg: string;
  };
  type Converter = (string) => StateInfo | undefined;
  const converter: Converter;
  export function fullName(string): string {}
  export function abbr(string): string {}
  export default converter;
}
`
then import  

`import { fullName,  abbr} from 'us-state-converter'`

**Comment by Dmitriyx** [comment]
make pull request

**Comment by FrenchMajesty** [comment]
@keveightysev Any chance to have this merged in? Would be valuable for the community

**Comment by keveightysev** [comment]
@khitrenovich @tharinduAppno @Dmitriyx @FrenchMajesty 

Apologies for the delay on getting this added. I just published an update to NPM with the declaration file
